name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for autofilm
        id: meta-autofilm
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/autofilm

      - name: Build and push autofilm image
        uses: docker/build-push-action@v5
        with:
          context: ./autofilm
          file: ./autofilm/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-autofilm.outputs.tags }}
          labels: ${{ steps.meta-autofilm.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for mediawarp
        id: meta-mediawarp
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/mediawarp

      - name: Build and push mediawarp image
        uses: docker/build-push-action@v5
        with:
          context: ./mediawarp
          file: ./mediawarp/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-mediawarp.outputs.tags }}
          labels: ${{ steps.meta-mediawarp.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 